### ISSUE TITLE
Geometry input crashes when not importing as reference

### ISSUE THREAD

**Issue by georgelam0306** [sideeffects/HoudiniEngineForUnreal-v2#106]
Getting this exception when I try to use 4.26 v2 plugin while trying to use geometry input

Assertion failed: 0 [File:C:\cygwin\home\prisms\builder-new\Nightly18.5CMakePython3\dev\engine\unreal\4.26-v2\Engine\Plugins\Runtime\HoudiniEngine\Source\HoudiniEngine\Private\UnrealMeshTranslator.cpp] [Line: 2043]

UE4Editor_Core
UE4Editor_Core
UE4Editor_HoudiniEngine
UE4Editor_HoudiniEngine
UE4Editor_HoudiniEngine
UE4Editor_HoudiniEngine
UE4Editor_HoudiniEngine
UE4Editor_HoudiniEngine
UE4Editor_HoudiniEngine
UE4Editor_HoudiniEngine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_UnrealEd
UE4Editor_UnrealEd
UE4Editor
UE4Editor
UE4Editor
UE4Editor
UE4Editor
kernel32
ntdll

**Comment by dpernuit** [comment]
Hi,

This issue should be fixed in tomorrow's daily build.
I just fixed a crash in the plugin around where your assertion was triggered, but I can't guarantee it's the exact same issue you had with the information you provided.

Please try tomorrow's daily build and let us know if your issue's fixed.
