### ISSUE TITLE
Plugin 'HoudiniEngine' failed to load because module 'HoudiniEngine' 

### ISSUE THREAD

**Issue by MAXXDREAMS-EXE** [sideeffects/HoudiniEngineForUnreal-v2#119]
Hi,

After installing the plugin I have appears a message:  http://joxi.ru/v29yOgoipkBpa2

Plugin 'HoudiniEngine' failed to load because module 'HoudiniEngine' could not be found.  Please ensure the plugin is properly installed, otherwise consider disabling the plugin for this project.

**Comment by yuhe00** [comment]
You're missing binaries. You could download the prebuilt binaries or generate projectfiles and build the plugin yourself.

**Comment by MAXXDREAMS-EXE** [comment]
Pls, tell me where I can download the prebuilt binaries? Last time I downloaded here - https://github.com/sideeffects/HoudiniEngineForUnreal

**Comment by varomixai** [comment]
They come with the Houdini installer now, not sure how up to date they are

**Comment by dpernuit** [comment]
The binaries can be downloaded on the release page of this repo:
https://github.com/sideeffects/HoudiniEngineForUnreal-v2/releases

The HoudiniEngineForUnreal repo you mentionned above is for version 1 of the plugin.

Alternatively, as Varomix mentioned, you can get the plugins binaries in the Houdini installer.
Though, since we ship both v1 and v2, you need to manually copy the version of the plugin you want to use.

The Houdini installer has the latest version of the plugin (daily builds), the git repository for v2 is currently only updated to match production builds.
