### ISSUE TITLE
Scripting support for automation

### ISSUE THREAD

**Issue by Bjorn-Darewise** [sideeffects/HoudiniEngineForUnreal-v2#30]
Hi,
In regards to automation, what are the options for example to change parameters through Unreal or Python? I can't seem to find options to automate setups.

Thank you,
Bjorn

**Comment by dpernuit** [comment]
Hi Bjorn,
This is something that we'll likely add once we have BP support.
BP support will come with some UFUNCTIONs to set parameters, inputs etc... which will normally expose them in python as well.

**Comment by eetumartola** [comment]
Sounds great! Please do not forget to add a function for cooking/rebuilding - and a blocking one at that if I can ask ;)

**Comment by RobbieStorm** [comment]
Hey, to add to this;
So far the UFUNCTIONS for parameter setting do not cover all attribute types yet. I also found these functions to be more useful in the HoudiniAssetComponent, instead of the HoudiniAssetBlueprintComponent. This way they can also be called on a HoudiniAssetActor. I tested this and it didn't break anything... (yet :) )
So will all attribute types be settable?
And will they stay in the blueprint component?
Cheers

**Comment by dpernuit** [comment]
Hi,

The plugin now has a Public API that exposes a lot of the plugin's functionalities to C++/BP/Python.
It allows you to set Parameters, Inputs, Instantiating / Cooking / Rebuilding assets etc... 

Docs:
https://www.sidefx.com/docs/unreal/_public_a_p_i.html

**Comment by Bjorn-Darewise** [comment]
Hi,
Thanks for sharing !

Kind regards,

Bjorn Klaassen
*Lead Technical Artist - Darewise Entertainment*
*Cell: +31.6.45.74.08.15*
27 rue de Mogador, 75009 Paris
***@***.*** ***@***.***>
