### ISSUE TITLE
Cannot Generate Mesh in Unreal and Houdini Sync Crash with plugin v2

### ISSUE THREAD

**Issue by monci1850** [sideeffects/HoudiniEngineForUnreal-v2#68]
Hi, I created a hda to generate some meshes with Houdini 18.0.597 and 18.5.351
When I drag hda into UE4.25 with v2 engine plugin, it cannot generate meshes.  Session problem I guess. The "create session" could not help.
I tried to open Houdini Sync, I found that in Houdini no new hda created.  
Then I clicked the hda in UE to activate it again, the Houdini Sync starts to load that hda and cook it. However, as soon as it finished the cooking(generate the mesh), the Houdini crashed immediately. 
I tried with 18.0.597 and 18.5.351, they both have this issue when using v2. 
If I switch back to v1, everything goes back to normal:  the mesh is generated, the session is running.

**Comment by dpernuit** [comment]
Hi,

We've fixed quite a few crashes in the latest beta2 update, so you might wanna try again with that update.
If the plugin fails to automatically create the session, one solution is to set the Houdini directory in the plugin's settings.
We do have a bug in the 4.25 plugin that prevents the plugin from properly detecting the H install dir in the registry.

If the crash is not fixed in beta2, would you be able to submit a bug for this, and send us your hda and ue4 logs with the bug?
